cvp.app.knime.ifcbuilding: # {group_id}.{name} from the knime.yml
  src: C:\Users\e.capasso\Documents\Repositories\CVP.App.Knime.IFCReader\ifcbuildingread # Path to folder containing the extension files
  conda_env_path: C:\Users\e.capasso\.conda\envs\my_python_env # Path to the Python environment to use
  debug_mode: true # Optional line, if set to true, it will always use the latest changes of execute/configure, when that method is used within the KNIME Analytics Platform