cvp.app.knime.bim: # {group_id}.{name} from the knime.yml
  src: <LOCAL_PATH_TO>\CVP.App.Knime.IFCReader\knime_extension # Path to folder containing the extension files
  conda_env_path: <LOCAL_PATH_TO>\my_python_env # Path to the Python environment to use
  debug_mode: true # Optional line, if set to true, it will always use the latest changes of execute/configure, when that method is used within the KNIME Analytics Platform