name: ifcreader
channels:
  - knime
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - knime-extension
  - knime-python-base
  - ifcopenshell
  - ucrt
  - platformdirs
  - python-dateutil
  - pip
  - pyzmq
  - backcall
  - pywin32
  - matplotlib-inline
  - setuptools
  - executing
  - psutil
  - zeromq
  - traitlets
  - zipp
  - importlib-metadata
  - jedi
  - jupyter_client
  - colorama
  - packaging
  - pure_eval
  - tzdata
  - six
  - typing_extensions
  - python_abi
  - prompt_toolkit
  - wcwidth
  - backports
  - pickleshare
  - importlib_metadata
  - prompt-toolkit
  - stack_data
  - ipython
  - tk
  - nest-asyncio
  - libsodium
  - jupyter_core
  - debugpy
  - openssl
  - libsqlite
  - libffi
  - wheel
  - asttokens
  - pygments
  - vc14_runtime
  - parso
  - ca-certificates
  - vc
  - vs2015_runtime
  - comm
  - libzlib
  - tornado
  - typing-extensions
  - decorator
  - xz
  - backports.functools_lru_cache
  - bzip2
  - ipykernel